// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiuFNd82ue4AntwYAZ4LHIFwlALGLPu9s',
    appId: '1:427530459983:web:95ca3029a7692657f9c33a',
    messagingSenderId: '427530459983',
    projectId: 'pmj-application',
    authDomain: 'pmj-application.firebaseapp.com',
    storageBucket: 'pmj-application.firebasestorage.app',
    measurementId: 'G-ECSMRHKLEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj8oUbDB1h2ldziveyuafffX_8TXQucy4',
    appId: '1:427530459983:android:287a3e590407fc58f9c33a',
    messagingSenderId: '427530459983',
    projectId: 'pmj-application',
    storageBucket: 'pmj-application.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzGaF8Vg_Zzb2QyLtZ1zVamljW9l6AoeQ',
    appId: '1:427530459983:ios:b3e32c3a047e1f1ef9c33a',
    messagingSenderId: '427530459983',
    projectId: 'pmj-application',
    storageBucket: 'pmj-application.firebasestorage.app',
    iosClientId: '427530459983-um1kojml8gbsbfemf9nk31uvd7ltilob.apps.googleusercontent.com',
    iosBundleId: 'com.example.pmjApplication',
  );
}
